# Generated by Django 4.2 on 2023-04-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('pdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
